//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitimProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egitmenler()
        {
            this.Siparis = new HashSet<Siparis>();
            this.Videolar1 = new HashSet<Videolar>();
        }
    
        public int egt_id { get; set; }
        public string egt_ad { get; set; }
        public string egt_soyad { get; set; }
        public string egt_eposta { get; set; }
        public string egt_sifre { get; set; }
        public string egt_tel { get; set; }
        public Nullable<int> egt_puan { get; set; }
        public Nullable<int> egt_video { get; set; }
    
        public virtual Puanlar Puanlar { get; set; }
        public virtual Videolar Videolar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Videolar> Videolar1 { get; set; }
    }
}
