//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitimProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int sepet_id { get; set; }
        public string fiyat { get; set; }
        public Nullable<int> video_id { get; set; }
    
        public virtual Videolar Videolar { get; set; }
    }
}
