//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEgitimProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisId { get; set; }
        public int OgrenciId { get; set; }
        public int EgitmenId { get; set; }
        public System.DateTime SiparisTarih { get; set; }
        public Nullable<int> video_id { get; set; }
    
        public virtual Egitmenler Egitmenler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
        public virtual Videolar Videolar { get; set; }
    }
}
